Initial documentation
stickianempire/stickian pull request #1
Opened 2022-10-12 21:31 UTC by MrToino

Added initial documentation such as CODEOWNERS, README and CODEOFCONDUCT.

2022-10-12 22:33 UTC, luisferreira32 requested changes
All these documents should live at the root of the repo (LICENSE and CODEOWNERS for sure, otherwise it will "break" their fancy features)

2022-10-12 22:33 UTC, luisferreira32 commented on documents/CODEOWNERS
> +*       @MrToino @luisferreira32 @bgonilho
Add a newline at the end

2022-10-12 23:20 UTC, MrToino commented on documents/CODEOWNERS
> +*       @MrToino @luisferreira32 @bgonilho
Solved

2022-10-13 17:16 UTC, luisferreira32 approved these changes

2022-10-13 21:58 UTC, merged